### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

### ISSUE THREAD

**Issue by NickITGuy** [endreszabo/PowerDNS-Dynamic-Reverse-Backend#4]
Hi!

Trying to setup this on a fresh vm have everything setup correctly but the script is failing on this issue.

YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

Happy to provide logs, system is Ubuntu 20.04

**Comment by endreszabo** [comment]
Hi and thanks for reporting this.

Can you please provide me with the version of ruamel yaml installed?

**Comment by NickITGuy** [comment]
Hi,

I believe its these ones if I am understanding correctly.

```
Requirement already satisfied: ruamel.yaml in /usr/local/lib/python2.7/dist-packages (0.16.13)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" in /usr/local/lib/python2.7/dist-packages (from ruamel.yaml) (0.2.2)
Requirement already satisfied: ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" in /usr/local/lib/python2.7/dist-packages (from ruamel.yaml) (0.4.15)
```

**Comment by endreszabo** [comment]
Ok, I see you use python2 and as such, I can't test this legacy code for you.

My best idea is to change the line 248 of:
```
        config_dict = yaml.load(config_file)
```
to
```
        config_dict = yaml.load(config_file, Loader=yaml.FullLoader)
```

I'll port this functionality to my other, way better maintained project called `pdnsapp` which is a general purpose python framework for PowerDNS. The backside for you is that it runs on python3 only as far as I'm aware.

**Comment by NickITGuy** [comment]
Oh right I had problems with this script not this error but from memory another issue when trying python3 but I will start fresh tomorrow and see how it goes.

Thanks :)

Thanks,
Nicholas Davis,
M: 0438607040
________________________________

**Comment by NickITGuy** [comment]
Hi @endreszabo,

I've tried again today and it seems that the same error does persist on python3, I will post again if your recommended fix works. :)

**Comment by NickITGuy** [comment]
I got the error for the python file specifically to go away but for the life of me I cant figure out why PDNS still fails with an error, anyhelp would be greatly appreciated. :)

```
● pdns.service - PowerDNS Authoritative Server
     Loaded: loaded (/lib/systemd/system/pdns.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2021-07-08 12:18:22 UTC; 818ms ago
       Docs: man:pdns_server(1)
             man:pdns_control(1)
             https://doc.powerdns.com
    Process: 13168 ExecStart=/usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --log-timestamp=no --writ>
   Main PID: 13168 (code=exited, status=1/FAILURE)

Jul 08 12:18:22 ns1.akora.network systemd[1]: pdns.service: Main process exited, code=exited, status=1/FAILURE
Jul 08 12:18:22 ns1.akora.network systemd[1]: pdns.service: Failed with result 'exit-code'.
Jul 08 12:18:22 ns1.akora.network systemd[1]: Failed to start PowerDNS Authoritative Server.
```

**Comment by NickITGuy** [comment]
Actually scratch that! I have it all working now.

If anyone reads this in the future dont be like me and make sure you install pdns-backend-pipe 🤦
